- ignore:
    name: "Use newtype instead of data"
- ignore:
    name: "Use <$>"
- ignore:
    name: "Redundant <$>"
- ignore:
    name: "Use ++"
- ignore:
    name: "Use &&"
- ignore:
    name: "Use tuple-section"
- ignore:
    name: "Use unless"
- ignore:
    name: "Redundant fmap"
    within: OptEnvConf.RunSpec
