snapshot: lts-24.38
packages: 
- opt-env-conf
- opt-env-conf-test
- opt-env-conf-example

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -O0 -Wunused-packages

extra-deps:
- github: NorfairKing/safe-coloured-text
  commit: b228e0e8dabf628581a56240aefc3e6e1b3694e6
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-gen
- github: NorfairKing/autodocodec
  commit: 825b5583ae9826e468f516ddfe32a4b26f68aa8e
  subdirs:
    - autodocodec
    - autodocodec-yaml
    - autodocodec-schema
    - autodocodec-nix

system-ghc: true
nix:
  enable: false
with-hpack: hpack
