snapshot: lts-22.22
packages: 
- opt-env-conf
- opt-env-conf-test
- opt-env-conf-example

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -O0 -Wunused-packages

extra-deps:
- github: NorfairKing/safe-coloured-text
  commit: 046f10147a058c00c2706d98c341219e3cbc7669
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-gen
- github: NorfairKing/autodocodec
  commit: be4aba9ef133520a8a4087aa26915aaabf1376a7
  subdirs:
    - autodocodec
    - autodocodec-yaml
    - autodocodec-schema
    - autodocodec-nix

# system-ghc: true
# nix:
#   enable: false
# with-hpack: hpack
