snapshot: lts-24.16
packages: 
- opt-env-conf
- opt-env-conf-test
- opt-env-conf-example

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -O0 -Wunused-packages

extra-deps:
- github: NorfairKing/safe-coloured-text
  commit: cc3666b9663a406583c6f7cdfccdfeb6dd2a0b10
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-gen
- github: NorfairKing/autodocodec
  commit: ac2c02071d7da65b09b3ccfe41c0b60a07794d68
  subdirs:
    - autodocodec
    - autodocodec-yaml
    - autodocodec-schema
    - autodocodec-nix

system-ghc: true
nix:
  enable: false
with-hpack: hpack
