snapshot: lts-22.22
packages: 
- opt-env-conf
- opt-env-conf-test
- opt-env-conf-example

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -O0 -Wunused-packages

extra-deps:
- github: NorfairKing/safe-coloured-text
  commit: 61f14d21b7399fe97da24e484c2f9fedaf532bb8
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-gen
- github: NorfairKing/autodocodec
  commit: c51eaad56acb0f9e6fa68ae7c1a14ba9dd8650c6
  subdirs:
    - autodocodec
    - autodocodec-yaml
    - autodocodec-schema
    - autodocodec-nix

system-ghc: true
nix:
  enable: false
with-hpack: hpack
