name: opt-env-conf-test
version: '0.0.0.0'
github: "NorfairKing/opt-env-conf"
copyright: ! 'Copyright: (c) 2024 Tom Sydney Kerckhove'
license: OtherLicense
license-file: LICENSE.md
synopsis: A testing companion package for opt-env-conf
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
  
extra-source-files:
- CHANGELOG.md
- test_resources/**/*

dependencies:
- base <5


library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - genvalidity
  - genvalidity-containers
  - opt-env-conf
  - safe-coloured-text
  - sydtest
  - text

executables:
  opt-env-conf-example:
    main: Main.hs
    source-dirs: app
    dependencies:
    - opt-env-conf
    - text

tests:
  opt-env-conf-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - aeson 
    - autodocodec
    - containers
    - genvalidity-aeson
    - genvalidity-sydtest
    - genvalidity-text
    - mtl
    - opt-env-conf
    - opt-env-conf-test
    - path
    - pretty-show
    - safe-coloured-text
    - sydtest
    - text
