# DO NOT EDIT THIS FILE DIRECTLY
# This file was generated by
# opt-env-conf-test:test/OptEnvConf/APISpec.hs:38
# To update this it, run the test with --golden-reset
{ lib }:
{
  enable = lib.mkOption {
    default = null;
    description = "enable extra";
    type = lib.types.nullOr lib.types.bool;
  };
  number = lib.mkOption {
    default = null;
    description = "number";
    type = lib.types.nullOr lib.types.int;
  };
}
