# DO NOT EDIT THIS FILE DIRECTLY
# This file was generated by
# opt-env-conf-test:test/OptEnvConf/APISpec.hs:39
# To update this it, run the test with --golden-reset
{ lib }:
{
  name = lib.mkOption {
    default = null;
    description = "name";
    type = lib.types.nullOr lib.types.str;
  };
}
