# DO NOT EDIT THIS FILE DIRECTLY
# This file was generated by
# opt-env-conf-test:test/OptEnvConf/APISpec.hs:26
# To update this it, run the test with --golden-reset
{ lib }:
{
  foo = lib.mkOption {
    default = { };
    type = lib.types.submodule {
      options = {
        bar = lib.mkOption {
          default = { };
          type = lib.types.submodule {
            options = {
              quux = lib.mkOption {
                default = null;
                description = "Example with sub-settings";
                type = lib.types.nullOr lib.types.str;
              };
            };
          };
        };
      };
    };
  };
}
