# DO NOT EDIT THIS FILE DIRECTLY
# This file was generated by
# opt-env-conf-test:test/OptEnvConf/APISpec.hs:34
# To update this it, run the test with --golden-reset
{ lib }:
{
  sum-type = lib.mkOption {
    default = null;
    description = "example";
    type = lib.types.nullOr lib.types.str;
  };
}
