# DO NOT EDIT THIS FILE DIRECTLY
# This file was generated by
# opt-env-conf-test:test/OptEnvConf/APISpec.hs:35
# To update this it, run the test with --golden-reset
{ lib }:
{
  first-secret-file = lib.mkOption {
    default = null;
    description = "First example secret";
    type = lib.types.nullOr lib.types.str;
  };
  second-secret = lib.mkOption {
    default = null;
    description = "Second example secret, bare or in a file, only conf";
    type = lib.types.nullOr lib.types.str;
  };
  second-secret-file = lib.mkOption {
    default = null;
    description = "Second example secret, bare or in a file, only conf";
    type = lib.types.nullOr lib.types.str;
  };
}
