# DO NOT EDIT THIS FILE DIRECTLY
# This file was generated by
# opt-env-conf-test:test/OptEnvConf/APISpec.hs:25
# To update this it, run the test with --golden-reset
{ lib }:
{
  big = lib.mkOption {
    default = null;
    description = "big configuration object";
    type = lib.types.nullOr (lib.types.submodule {
      options = {
        map = lib.mkOption {
          type = lib.types.attrsOf (lib.types.attrsOf lib.types.int);
        };
        sub = lib.mkOption {
          default = null;
          type = lib.types.nullOr lib.types.str;
        };
      };
    });
  };
}
