name: opt-env-conf
version: '0.11.0.0'
github: "NorfairKing/opt-env-conf"
copyright: ! 'Copyright: (c) 2024-2025 Tom Sydney Kerckhove'
license: LGPL-3
license-file: LICENSE
synopsis: 'Settings parsing for Haskell: command-line arguments, environment variables, and configuration values.'
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"

extra-source-files:
- CHANGELOG.md

dependencies:
- base <5

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - aeson
  - autodocodec >= 0.3.0.0
  - autodocodec-nix
  - autodocodec-schema
  - autodocodec-yaml
  - containers
  - hashable
  - mtl
  - path
  - path-io
  - path-io
  - safe-coloured-text >= 0.3.0.2
  - safe-coloured-text-layout >= 0.2.0.0
  - selective
  - text
  - validity
  - validity-containers
  when:
    - condition: "!os(windows)"
      dependencies:
        - safe-coloured-text-terminfo
