name: opt-env-conf
version: '0.0.0.0'
copyright: ! 'Copyright: (c) 2024 Tom Sydney Kerckhove'
license: LGPL-3
license-file: LICENSE
synopsis: 'Settings parsing for Haskell: command-line arguments, environment variables, and configuration values.'
 
extra-source-files:
- CHANGELOG.md

dependencies:
- base <5

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - aeson
  - autodocodec >= 0.2.3.0
  - autodocodec-schema
  - autodocodec-yaml
  - containers
  - hashable
  - mtl
  - path
  - path-io
  - safe-coloured-text >= 0.3.0.2
  - safe-coloured-text-layout >= 0.2.0.0
  - safe-coloured-text-terminfo # TODO Don't depend on this on windows
  - selective
  - text
  - validity
  - validity-containers
