# DO NOT EDIT THIS FILE DIRECTLY
# This file was generated by
# opt-env-conf-test:test/OptEnvConf/APISpec.hs:33
# To update this it, run the test with --golden-reset
{ lib }:
{
  int = lib.mkOption {
    default = null;
    description = "int or string";
    type = lib.types.nullOr lib.types.int;
  };
  other = lib.mkOption {
    default = null;
    description = "int or string";
    type = lib.types.nullOr lib.types.bool;
  };
  string = lib.mkOption {
    default = null;
    description = "int or string";
    type = lib.types.nullOr lib.types.str;
  };
}
