# DO NOT EDIT THIS FILE DIRECTLY
# This file was generated by
# opt-env-conf-test:test/OptEnvConf/APISpec.hs:31
# To update this it, run the test with --golden-reset
{ lib }:
{
  example = lib.mkOption {
    default = null;
    description = "Example of a yes/no switch";
    type = lib.types.nullOr lib.types.bool;
  };
}
