# DO NOT EDIT THIS FILE DIRECTLY
# This file was generated by
# opt-env-conf-test:test/OptEnvConf/APISpec.hs:37
# To update this it, run the test with --golden-reset
{ lib }:
{
  greeting = lib.mkOption {
    default = null;
    description = "Greeting to use";
    type = lib.types.nullOr lib.types.str;
  };
  polite = lib.mkOption {
    default = null;
    description = "Whether to be polite";
    type = lib.types.nullOr lib.types.bool;
  };
}
